from typing import Any, ContextManager, Optional, Protocol


class StorageProtocol(Protocol):
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def delete(self, key: str) -> None: ...
    def locked(self, key: Optional[str] = None) -> ContextManager[None]: ...


class KeyResolverProtocol(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> str: ...
